import { Column } from "@/components/tables/DataTable";
import { Lab } from "@/lib/types";

export const materialColumns: Column<Lab>[] = [
	{ header: "ID", accessor: "id" },
	{ header: "Customer Description", accessor: "customerDescription" },
	{ header: "Street House Number", accessor: "customerStreetHouseNumber" },
	{ header: "Land", accessor: "customerLand" },
	{ header: "Zip Code", accessor: "customerZipCode" },
	{ header: "City", accessor: "customerCity" },
	{ header: "Contact Person", accessor: "customerContactPersonName" },
	{ header: "Purchasing Group", accessor: "customerPurchasingGroup" },
	{ header: "Identification", accessor: "customerIdentification" },
	{ header: "Phone", accessor: "customerPhone" },
	{ header: "Fax", accessor: "customerFax" },
	{ header: "Email", accessor: "customerEmail" },
	{ header: "VAT", accessor: "customerVat" },
	{ header: "Customer Number", accessor: "customerNumber" },
	{ header: "Supplier Number", accessor: "supplierNumber" },
	{ header: "Client Number", accessor: "clientNumber" },
	{ header: "Plant Number", accessor: "plantNumber" },
	{ header: "Plant Description", accessor: "plantDescription" },
	{ header: "Unloading Point", accessor: "unloadingPoint" },
	{ header: "Storage Point", accessor: "storagePoint" },
	{ header: "Consumption Point", accessor: "consumptionPoint" },
	{ header: "Current Lab Number", accessor: "currentLabNumber" },
	{ header: "Current Lab Date", accessor: "currentLabDate" },
	{ header: "Last Lab Number", accessor: "lastLabNumber" },
	{ header: "Last Lab Date", accessor: "lastLabDate" },
	{ header: "Part Number", accessor: "partNumber" },
	{ header: "Material Description", accessor: "materialDescription" },
	{ header: "Production Release Date", accessor: "productionReleaseDate" },
	{ header: "Material Release Date", accessor: "materialReleaseDate" },
	{ header: "Order Number", accessor: "orderNumber" },
	{ header: "Free Text", accessor: "freeText" },
	{ header: "Unit of Measure", accessor: "unitOfMeasure" },
	{ header: "Input Progress Count", accessor: "inputProgressCount" },
	{ header: "Start Date EFZ", accessor: "startDateEfz" },
	{ header: "Reset EFZ", accessor: "resetEfz" },
	{ header: "Status", accessor: "status" },
	{ header: "Read At", accessor: "readAt" },
	{ header: "In Progress From", accessor: "inProgressFrom" },
	{ header: "Closed At", accessor: "closedAt" },
	{ header: "EDI Message Key", accessor: "ediMessageKey" },
	{ header: "Overtake Number", accessor: "overtakeNumber" },
	{ header: "Overtake Date", accessor: "overtakeDate" },
	{ header: "Updated At", accessor: "updatedAt" },
	{ header: "Updated By", accessor: "updatedBy" },
	{ header: "Created At", accessor: "createdAt" },
	{ header: "Created By", accessor: "createdBy" },
	{ header: "Deletion Mark", accessor: "deletionMark" },
	{ header: "Lab ID", accessor: "labId" },
	{ header: "Lab Flag", accessor: "labFlag" },
	{ header: "Key", accessor: "key" },
	{ header: "Order Position", accessor: "orderPosition" },
];
