import type { Metadata } from "next";
import "./globals.css";
import { heptaSlab } from "@/assets/fonts";
import { ThemeProvider } from "@/components/theme/ThemeProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="cs"
			suppressHydrationWarning>
			<body className={`${heptaSlab.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
